#!/bin/sh 

case $1 in
    "*") command="";;
    "up") command="change +4%";;
    "down") command="change -4%";;
    "toggle") command="mute toggle";;
esac

[ -n "$command" ] && pw-volume $command

$2 update volume=$(pw-volume status | jq '.percentage // 10')
